spring:
  application:
    name: kfreemarket

  datasource:
    url: jdbc:mysql://localhost:3306/kfreemarket
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
